language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
  - cd DiscordChatBot
  - dotnet restore
  - dotnet test ./DiscordChatBotTests/
deploy:
  provider: azure_web_app
  skip_cleanup: true