FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app
RUN ls -a
COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish --runtime win10-x64 -c Release -o out

FROM microsoft/aspnetcore:2.0
WORKDIR /app
Copy --from=build-env /app/out .
ENTRYPOINT ["dotnet", "DiscordChatBot.exe"]